/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Billboard;
import model.User;

/**
 *
 * @author Asus
 */
public class EditUserPage extends javax.swing.JFrame {

    
    private ArrayList<User> listUser;
    DefaultTableModel model;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private int selectedIndex;
    /**
     * Creates new form EditUserPage
     */
    public EditUserPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        createUserPanel.setVisible(false);
        editUserPanel.setVisible(false);
        
        createUserPanel.setVisible(false);
        listUser = new DAO().getListUser();
        model = (DefaultTableModel) userTable.getModel();
        model.setColumnIdentifiers(new Object[] {
            "User ID", "Username", "Password", "Permission","Created at", "Update at"
        });
        showTable();
    }
    
    public void addUser (User u) {
        listUser.add(u);
        showTable();  
    }
    
    
    public void showTable() {
        model.setRowCount(0); //reset content in table to 0
        for (User u : listUser) {
            model.addRow(new Object[]{
                u.getUserId(), u.getUsername(), u.getPassword(), u.getPermission(), u.getCreatedAt(), u.getUpdateAt()
            });
            
            
        }
    }
    
    public static String removeLastChar(String s) {
    return (s == null || s.length() == 0)
      ? null
      : (s.substring(0, s.length() - 1));
    }
    
    public void setEditData(User u) {
        txtEditUserId.setText( Integer.toString(u.getUserId()));
        txtEditUsername.setText(u.getUsername());        
        txtEditPassword.setText(u.getPassword());
        
        ArrayList<String> permission = u.getPermission();
        if (permission.contains("CB")) {
            cbCreate1.setSelected(true);
        }
        if (permission.contains("EB")) {
            cbEditBb1.setSelected(true);
        }
        if (permission.contains("SB")) {
            cbSchedule1.setSelected(true);
        }
        if (permission.contains("EU")) {
            cbEditUser1.setSelected(true);
        }
        
    }
    
    public int getCurrentUserId() {
        ArrayList<Integer> userId = new ArrayList<Integer>();
        for (User u: listUser){
            userId.add(u.getUserId());
        }
        
        return Collections.max(userId); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        btn_create_billboards = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_list_billboards = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lb_list_billboards = new javax.swing.JLabel();
        btn_schedule_billboards = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lb_schedule_billboards = new javax.swing.JLabel();
        btn_edit_users = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lb_edit_users = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnDeleteTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        btnEditTable = new javax.swing.JButton();
        btnAddTabel = new javax.swing.JButton();
        editUserPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtEditUsername = new javax.swing.JTextField();
        btnCancelEdit = new javax.swing.JButton();
        btnSaveEdit = new javax.swing.JButton();
        txtEditPassword = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        txtEditCheckPassword = new javax.swing.JPasswordField();
        cbCreate1 = new javax.swing.JCheckBox();
        cbEditBb1 = new javax.swing.JCheckBox();
        cbEditUser1 = new javax.swing.JCheckBox();
        cbSchedule1 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        txtEditUserId = new javax.swing.JTextField();
        createUserPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        txtCheckPassword = new javax.swing.JPasswordField();
        cbCreate = new javax.swing.JCheckBox();
        cbEditBb = new javax.swing.JCheckBox();
        cbEditUser = new javax.swing.JCheckBox();
        cbSchedule = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setPreferredSize(new Dimension(screenSize.width / 5, screenSize.height));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("BBCreator");
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btn_home.setBackground(new java.awt.Color(64, 43, 100));
        btn_home.setPreferredSize(new Dimension(screenSize.width / 5, 50) );
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homejLabel1MousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_home_15px_1.png")); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(204, 204, 204));
        lb_home.setText("Home");
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_homejLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_home)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_home)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 384, 50));

        btn_create_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_create_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_create_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_create_15px.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Create Billboards");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_create_billboardsLayout = new javax.swing.GroupLayout(btn_create_billboards);
        btn_create_billboards.setLayout(btn_create_billboardsLayout);
        btn_create_billboardsLayout.setHorizontalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_create_billboardsLayout.setVerticalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        sidepanel.add(btn_create_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 384, 50));

        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_list_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_list_15px.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        lb_list_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_list_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_list_billboards.setText("List Billboards");
        lb_list_billboards.setToolTipText("");
        lb_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_list_billboardsLayout = new javax.swing.GroupLayout(btn_list_billboards);
        btn_list_billboards.setLayout(btn_list_billboardsLayout);
        btn_list_billboardsLayout.setHorizontalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_list_billboards)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btn_list_billboardsLayout.setVerticalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_list_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btn_list_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 384, 50));

        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_schedule_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_schedule_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardslb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardslb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardsMousePressed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_schedule_15px_1.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14lb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14lb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardsMousePressed(evt);
            }
        });

        lb_schedule_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_schedule_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_schedule_billboards.setText("Schedule Billboards");
        lb_schedule_billboards.setToolTipText("");
        lb_schedule_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_schedule_billboardsLayout = new javax.swing.GroupLayout(btn_schedule_billboards);
        btn_schedule_billboards.setLayout(btn_schedule_billboardsLayout);
        btn_schedule_billboardsLayout.setHorizontalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_schedule_billboards)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        btn_schedule_billboardsLayout.setVerticalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_schedule_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepanel.add(btn_schedule_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 384, 50));

        btn_edit_users.setBackground(new java.awt.Color(85, 65, 118));
        btn_edit_users.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_edit_profile_15px_1.png")); // NOI18N

        lb_edit_users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_edit_users.setForeground(new java.awt.Color(204, 204, 204));
        lb_edit_users.setText("Edit Users");
        lb_edit_users.setToolTipText("");

        javax.swing.GroupLayout btn_edit_usersLayout = new javax.swing.GroupLayout(btn_edit_users);
        btn_edit_users.setLayout(btn_edit_usersLayout);
        btn_edit_usersLayout.setHorizontalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_edit_users)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        btn_edit_usersLayout.setVerticalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(lb_edit_users, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        sidepanel.add(btn_edit_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 384, 50));

        rootPanel.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 384, 1080));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("User List");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnDeleteTable.setBackground(new java.awt.Color(90, 148, 210));
        btnDeleteTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteTable.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTable.setText("Delete");
        btnDeleteTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDeleteTable.setBorderPainted(false);
        btnDeleteTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTableActionPerformed(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Username", "Password", "Permission", "Created at", "Update at"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        btnEditTable.setBackground(new java.awt.Color(90, 148, 210));
        btnEditTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditTable.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTable.setText("Edit");
        btnEditTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditTable.setBorderPainted(false);
        btnEditTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTableActionPerformed(evt);
            }
        });

        btnAddTabel.setBackground(new java.awt.Color(90, 148, 210));
        btnAddTabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAddTabel.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTabel.setText("Add");
        btnAddTabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddTabel.setBorderPainted(false);
        btnAddTabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addComponent(btnEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(btnAddTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        rootPanel.add(listPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 970, 660));

        editUserPanel.setBackground(new java.awt.Color(250, 250, 250));
        editUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(90, 148, 210));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Edit user");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(90, 148, 210));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Username");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(90, 148, 210));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Password");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(90, 148, 210));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Permission");

        txtEditUsername.setBackground(new java.awt.Color(250, 250, 250));
        txtEditUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        btnCancelEdit.setBackground(new java.awt.Color(90, 148, 210));
        btnCancelEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancelEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEdit.setText("Cancel");
        btnCancelEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelEdit.setBorderPainted(false);
        btnCancelEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditActionPerformed(evt);
            }
        });

        btnSaveEdit.setBackground(new java.awt.Color(90, 148, 210));
        btnSaveEdit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSaveEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveEdit.setText("Save");
        btnSaveEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSaveEdit.setBorderPainted(false);
        btnSaveEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        txtEditPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        txtEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditPasswordActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(90, 148, 210));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Re-enter password");

        txtEditCheckPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditCheckPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        txtEditCheckPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditCheckPasswordActionPerformed(evt);
            }
        });

        cbCreate1.setBackground(new java.awt.Color(250, 250, 250));
        cbCreate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCreate1.setForeground(new java.awt.Color(12, 91, 160));
        cbCreate1.setText("Create Billboards");
        cbCreate1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreate1ActionPerformed(evt);
            }
        });

        cbEditBb1.setBackground(new java.awt.Color(250, 250, 250));
        cbEditBb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEditBb1.setForeground(new java.awt.Color(12, 91, 160));
        cbEditBb1.setText("Edit All Billboards");
        cbEditBb1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbEditBb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditBb1ActionPerformed(evt);
            }
        });

        cbEditUser1.setBackground(new java.awt.Color(250, 250, 250));
        cbEditUser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEditUser1.setForeground(new java.awt.Color(12, 91, 160));
        cbEditUser1.setText("Edit Users");
        cbEditUser1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbEditUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditUser1ActionPerformed(evt);
            }
        });

        cbSchedule1.setBackground(new java.awt.Color(250, 250, 250));
        cbSchedule1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbSchedule1.setForeground(new java.awt.Color(12, 91, 160));
        cbSchedule1.setText("Schedule Billboards");
        cbSchedule1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbSchedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSchedule1ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(90, 148, 210));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("User ID");

        txtEditUserId.setEditable(false);
        txtEditUserId.setBackground(new java.awt.Color(250, 250, 250));
        txtEditUserId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEditUserId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        javax.swing.GroupLayout editUserPanelLayout = new javax.swing.GroupLayout(editUserPanel);
        editUserPanel.setLayout(editUserPanelLayout);
        editUserPanelLayout.setHorizontalGroup(
            editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(editUserPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editUserPanelLayout.createSequentialGroup()
                        .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(editUserPanelLayout.createSequentialGroup()
                        .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEditCheckPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCreate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEditBb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEditUser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSchedule1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUserPanelLayout.createSequentialGroup()
                        .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEditUserId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editUserPanelLayout.createSequentialGroup()
                                .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editUserPanelLayout.createSequentialGroup()
                                .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))))
        );
        editUserPanelLayout.setVerticalGroup(
            editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUserPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEditCheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCreate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditBb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSchedule1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditUser1)
                .addGap(30, 30, 30)
                .addGroup(editUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        rootPanel.add(editUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 360, 470, 660));

        createUserPanel.setBackground(new java.awt.Color(250, 250, 250));
        createUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(90, 148, 210));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Create new user");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(90, 148, 210));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Username");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(90, 148, 210));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Password");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(90, 148, 210));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Permission");

        txtUsername.setBackground(new java.awt.Color(250, 250, 250));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        btnCancel.setBackground(new java.awt.Color(90, 148, 210));
        btnCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(90, 148, 210));
        btnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(90, 148, 210));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Re-enter password");

        txtCheckPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCheckPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        txtCheckPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckPasswordActionPerformed(evt);
            }
        });

        cbCreate.setBackground(new java.awt.Color(250, 250, 250));
        cbCreate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCreate.setForeground(new java.awt.Color(12, 91, 160));
        cbCreate.setText("Create Billboards");
        cbCreate.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreateActionPerformed(evt);
            }
        });

        cbEditBb.setBackground(new java.awt.Color(250, 250, 250));
        cbEditBb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEditBb.setForeground(new java.awt.Color(12, 91, 160));
        cbEditBb.setText("Edit All Billboards");
        cbEditBb.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbEditBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditBbActionPerformed(evt);
            }
        });

        cbEditUser.setBackground(new java.awt.Color(250, 250, 250));
        cbEditUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEditUser.setForeground(new java.awt.Color(12, 91, 160));
        cbEditUser.setText("Edit Users");
        cbEditUser.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditUserActionPerformed(evt);
            }
        });

        cbSchedule.setBackground(new java.awt.Color(250, 250, 250));
        cbSchedule.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbSchedule.setForeground(new java.awt.Color(12, 91, 160));
        cbSchedule.setText("Schedule Billboards");
        cbSchedule.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));
        cbSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbScheduleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createUserPanelLayout = new javax.swing.GroupLayout(createUserPanel);
        createUserPanel.setLayout(createUserPanelLayout);
        createUserPanelLayout.setHorizontalGroup(
            createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(createUserPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createUserPanelLayout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(createUserPanelLayout.createSequentialGroup()
                        .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addGroup(createUserPanelLayout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createUserPanelLayout.createSequentialGroup()
                                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))
                    .addGroup(createUserPanelLayout.createSequentialGroup()
                        .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCheckPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEditBb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEditUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSchedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        createUserPanelLayout.setVerticalGroup(
            createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUserPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditBb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEditUser)
                .addGap(95, 95, 95)
                .addGroup(createUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        rootPanel.add(createUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 360, 470, 660));

        jLabel2.setBackground(new java.awt.Color(245, 245, 245));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\bg_blue.png")); // NOI18N
        rootPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 250, 1536, 830));

        jPanel3.setBackground(new java.awt.Color(110, 89, 222));
        jPanel3.setPreferredSize(new Dimension(screenSize.width / 5 * 4, 150 ));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Edit Users");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Modify users' information as you wish");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addContainerGap(919, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        rootPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 90, 1610, 160));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("We ♥ BBCreator");
        rootPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        rootPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel1btn_homeMouseEntered

    private void jLabel1btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel1btn_homeMouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    private void lb_homebtn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_homebtn_homeMouseEntered

    private void lb_homebtn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_homebtn_homeMouseExited

    private void lb_homejLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homejLabel1MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_homejLabel1MousePressed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homejLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homejLabel1MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_homejLabel1MousePressed

    private void jLabel14lb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14lb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel14lb_schedule_billboardsMouseEntered

    private void jLabel14lb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14lb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel14lb_schedule_billboardsMouseExited

    private void lb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_schedule_billboardsMouseEntered

    private void lb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_schedule_billboardsMouseExited

    private void btn_schedule_billboardslb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_schedule_billboardslb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_schedule_billboardslb_schedule_billboardsMouseEntered

    private void btn_schedule_billboardslb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_schedule_billboardslb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
     
    }//GEN-LAST:event_btn_schedule_billboardslb_schedule_billboardsMouseExited

    private void btnDeleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTableActionPerformed
        int removeIndex = userTable.getSelectedRow();
        if (removeIndex < 0) {
            JOptionPane.showMessageDialog(rootPanel, "Choose a billboard to delete");
        } else if (listUser.size() == 0) {
            JOptionPane.showMessageDialog(rootPanel, "No billboards to delete");
        } else {
            listUser.remove(removeIndex);
            showTable();
        }
    }//GEN-LAST:event_btnDeleteTableActionPerformed

    private void btnEditTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTableActionPerformed
        createUserPanel.setVisible(false);
        selectedIndex = userTable.getSelectedRow();
        if (listUser.size() == 0){
            JOptionPane.showMessageDialog(rootPanel, "Add more users to edit");
        }else if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(rootPanel, "Choose a user to start editting");
        }else {
            setEditData(listUser.get(selectedIndex));
            System.out.println(""+ selectedIndex +listUser.get(selectedIndex).getUsername() );
            editUserPanel.setVisible(true);
        }
    }//GEN-LAST:event_btnEditTableActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        createUserPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String username, password, checkPassword;
        ArrayList<String> permission = new ArrayList<String>();        
        boolean isOk = true;
        int id = getCurrentUserId();
        
        username = txtUsername.getText();
        password = txtPassword.getText();
        checkPassword = txtCheckPassword.getText();
        
        if (!password.equals(checkPassword)){
            isOk = false;
        }
        
        
        if (cbCreate.isSelected()) {
            permission.add("CB");
        }
        if (cbEditBb.isSelected()) {
            permission.add("EB");
        }
        if (cbSchedule.isSelected()){
            permission.add("SB");
        }
        if (cbEditUser.isSelected()){
            permission.add("EU");
        }
        
        
        
        if(isOk) {
            id = id + 1;
            Date date = new Date();
            User user = new User();
                user.setUserId(id);
                user.setUsername(username);
                user.setPassword(password);
                user.setPermission(permission);
                user.setCreatedAt(date);
                user.setUpdateAt(date);
            addUser(user);
            JOptionPane.showMessageDialog(rootPanel, "Add successfully");
            
            txtUsername.setText("");
            txtPassword.setText("");
            txtCheckPassword.setText("");
            cbCreate.setSelected(false);
            cbEditBb.setSelected(false);
            cbSchedule.setSelected(false);
            cbEditUser.setSelected(false);
            createUserPanel.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPanel, "Something is wrong");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void btnAddTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTabelActionPerformed
        createUserPanel.setVisible(true);
        editUserPanel.setVisible(false);
        
    }//GEN-LAST:event_btnAddTabelActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtCheckPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckPasswordActionPerformed

    private void cbCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCreateActionPerformed

    private void cbEditBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditBbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEditBbActionPerformed

    private void cbEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEditUserActionPerformed

    private void cbScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbScheduleActionPerformed

    private void btnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditActionPerformed
        editUserPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelEditActionPerformed

    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
         
        String username, password;
        ArrayList<String> permission = new ArrayList<String>();
        int userId;
        
        
        boolean isOk = true;
        
        
        userId = Integer.parseInt(txtEditUserId.getText());
        username = txtEditUsername.getText();
        password = txtEditPassword.getText();
        
        if (cbCreate1.isSelected()) {
            permission.add("CB");
        }
        if (cbEditBb1.isSelected()) {
            permission.add("EB");
        }
        if (cbSchedule1.isSelected()){
            permission.add("SB");
        }
        if (cbEditUser1.isSelected()){
            permission.add("EU");
        }
        
        
        
        if(isOk) {
            
            Date date = new Date();            
            for (User u: listUser){
                if (u.getUserId() == userId) {
                    u.setUsername(username);
                    u.setPassword(password);
                    u.setPermission(permission);
                    u.setUpdateAt(date);
                }
            }
            showTable();           
            
            JOptionPane.showMessageDialog(rootPanel, "Edit successfully");
            
            editUserPanel.setVisible(false);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnSaveEditActionPerformed

    private void txtEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditPasswordActionPerformed

    private void txtEditCheckPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditCheckPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditCheckPasswordActionPerformed

    private void cbCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCreate1ActionPerformed

    private void cbEditBb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditBb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEditBb1ActionPerformed

    private void cbEditUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEditUser1ActionPerformed

    private void cbSchedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSchedule1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSchedule1ActionPerformed

    private void btn_schedule_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_schedule_billboardsMousePressed
        new ScheduleBillboardsPage().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_schedule_billboardsMousePressed

    private void btn_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardsMouseEntered
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
        
    }//GEN-LAST:event_btn_list_billboardsMouseEntered

    private void btn_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardsMouseExited
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
        
    }//GEN-LAST:event_btn_list_billboardsMouseExited

    private void btn_list_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardsMousePressed
        new ListBillboardsPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_list_billboardsMousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        btn_create_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        btn_create_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        new CreateBillboardsPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTabel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelEdit;
    private javax.swing.JButton btnDeleteTable;
    private javax.swing.JButton btnEditTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JPanel btn_create_billboards;
    private javax.swing.JPanel btn_edit_users;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_list_billboards;
    private javax.swing.JPanel btn_schedule_billboards;
    private javax.swing.JCheckBox cbCreate;
    private javax.swing.JCheckBox cbCreate1;
    private javax.swing.JCheckBox cbEditBb;
    private javax.swing.JCheckBox cbEditBb1;
    private javax.swing.JCheckBox cbEditUser;
    private javax.swing.JCheckBox cbEditUser1;
    private javax.swing.JCheckBox cbSchedule;
    private javax.swing.JCheckBox cbSchedule1;
    private javax.swing.JPanel createUserPanel;
    private javax.swing.JPanel editUserPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_edit_users;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_list_billboards;
    private javax.swing.JLabel lb_schedule_billboards;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPasswordField txtCheckPassword;
    private javax.swing.JPasswordField txtEditCheckPassword;
    private javax.swing.JPasswordField txtEditPassword;
    private javax.swing.JTextField txtEditUserId;
    private javax.swing.JTextField txtEditUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
