package view;


import controller.DAO;
import java.awt.Dimension;
import java.awt.List;
import java.awt.Toolkit;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Billboard;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ListBillboardsPage extends javax.swing.JFrame {

    /**
     * Creates new form ListBillboardsPage
     */
    private ArrayList<Billboard> listBillboard;
    DefaultTableModel model;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private int selectedIndex;
    
    
    public ListBillboardsPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        inputPanel.setVisible(false);
        listBillboard = new DAO().getListBillboard();
        model = (DefaultTableModel) billboardTable.getModel();
        model.setColumnIdentifiers(new Object[] {
            "Billboard ID", "User ID", "Message", "Information", "Background color", "Font color", "Created at", "Update at", "Picture"
        });
        showTable();
        
        
    }
    
    public void addBillboard (Billboard b) {
        listBillboard.add(b);
        showTable();  
    }
    
    
    public void showTable() {
        model.setRowCount(0); //reset content in table to 0
        for (Billboard b : listBillboard) {
            model.addRow(new Object[]{
                b.getBillboardId(), b.getUserId(), b.getMessage(), b.getInformation(), b.getBackgroundColor(), b.getFontColor(), b.getCreatedAt(), b.getUpdateAt(), b.getPicture()
            });
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        rootPanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        btn_create_billboards = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_list_billboards = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lb_list_billboards = new javax.swing.JLabel();
        btn_schedule_billboards = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lb_schedule_billboards = new javax.swing.JLabel();
        btn_edit_users = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lb_edit_users = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnDeleteTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billboardTable = new javax.swing.JTable();
        btnEditTable = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        inputPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtPicture = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtBgColor = new javax.swing.JTextField();
        txtFontColor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInformation = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setBackground(new java.awt.Color(90, 148, 210));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("THE #1 BILLBOARD GENERATOR  ");

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("<html>Get the perfect billboard design!<br>Whatever your need,<br>we’ll help get it done.");
        jLabel20.setToolTipText("");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jTextField1.setBackground(new java.awt.Color(250, 250, 250));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 148, 210));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tell us about your billboard");

        jButton1.setBackground(new java.awt.Color(90, 148, 210));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 148, 210));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Name your billboard");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(90, 148, 210));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Describe your billboard");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(90, 148, 210));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Add inspiration image");

        jTextField4.setBackground(new java.awt.Color(250, 250, 250));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jTextField5.setBackground(new java.awt.Color(250, 250, 250));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(90, 148, 210));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Choose background color");

        jTextField6.setBackground(new java.awt.Color(250, 250, 250));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jTextField7.setBackground(new java.awt.Color(250, 250, 250));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(90, 148, 210));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Choose font color");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnAdd.setBackground(new java.awt.Color(90, 148, 210));
        btnAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setPreferredSize(new Dimension(screenSize.width / 5, screenSize.height));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("BBCreator");
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btn_home.setBackground(new java.awt.Color(64, 43, 100));
        btn_home.setPreferredSize(new Dimension(screenSize.width / 5, 50) );
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_home_15px_1.png")); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(204, 204, 204));
        lb_home.setText("Home");
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_home)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_home)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 384, 50));

        btn_create_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_create_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_create_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMousePressed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_create_15px.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Create Billboards");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_create_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_create_billboardsLayout = new javax.swing.GroupLayout(btn_create_billboards);
        btn_create_billboards.setLayout(btn_create_billboardsLayout);
        btn_create_billboardsLayout.setHorizontalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_create_billboardsLayout.setVerticalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        sidepanel.add(btn_create_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 384, 50));

        btn_list_billboards.setBackground(new java.awt.Color(85, 65, 118));
        btn_list_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_list_15px.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12lb_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12lb_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        lb_list_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_list_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_list_billboards.setText("List Billboards");
        lb_list_billboards.setToolTipText("");
        lb_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_list_billboardsLayout = new javax.swing.GroupLayout(btn_list_billboards);
        btn_list_billboards.setLayout(btn_list_billboardsLayout);
        btn_list_billboardsLayout.setHorizontalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_list_billboards)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btn_list_billboardsLayout.setVerticalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_list_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btn_list_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 384, 50));

        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_schedule_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_schedule_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardslb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_schedule_billboardslb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMousePressed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_schedule_15px_1.png")); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14lb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14lb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMousePressed(evt);
            }
        });

        lb_schedule_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_schedule_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_schedule_billboards.setText("Schedule Billboards");
        lb_schedule_billboards.setToolTipText("");
        lb_schedule_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_schedule_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_schedule_billboardsLayout = new javax.swing.GroupLayout(btn_schedule_billboards);
        btn_schedule_billboards.setLayout(btn_schedule_billboardsLayout);
        btn_schedule_billboardsLayout.setHorizontalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_schedule_billboards)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        btn_schedule_billboardsLayout.setVerticalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_schedule_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidepanel.add(btn_schedule_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 384, 50));

        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
        btn_edit_users.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_edit_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_usersjLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_usersjLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_edit_usersMousePressed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_edit_profile_15px_1.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_edit_usersMousePressed(evt);
            }
        });

        lb_edit_users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_edit_users.setForeground(new java.awt.Color(204, 204, 204));
        lb_edit_users.setText("Edit Users");
        lb_edit_users.setToolTipText("");
        lb_edit_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_edit_usersjLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_edit_usersjLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_edit_usersMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_edit_usersLayout = new javax.swing.GroupLayout(btn_edit_users);
        btn_edit_users.setLayout(btn_edit_usersLayout);
        btn_edit_usersLayout.setHorizontalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_edit_users)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        btn_edit_usersLayout.setVerticalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(lb_edit_users, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        sidepanel.add(btn_edit_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 384, 50));

        rootPanel.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 384, 1080));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Billboards List");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnDeleteTable.setBackground(new java.awt.Color(90, 148, 210));
        btnDeleteTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteTable.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteTable.setText("Delete");
        btnDeleteTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDeleteTable.setBorderPainted(false);
        btnDeleteTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTableActionPerformed(evt);
            }
        });

        billboardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Billboard ID", "User ID", "Message", "Information", "Background color", "Font color", "Created at", "Update at", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billboardTable);

        btnEditTable.setBackground(new java.awt.Color(90, 148, 210));
        btnEditTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditTable.setForeground(new java.awt.Color(255, 255, 255));
        btnEditTable.setText("Edit");
        btnEditTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditTable.setBorderPainted(false);
        btnEditTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTableActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(90, 148, 210));
        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btnEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        rootPanel.add(listPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 970, 660));

        inputPanel.setBackground(new java.awt.Color(250, 250, 250));
        inputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(90, 148, 210));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Tell us about your billboard");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(90, 148, 210));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Name your billboard");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(90, 148, 210));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Describe your billboard");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(90, 148, 210));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Add inspiration image");

        txtPicture.setBackground(new java.awt.Color(250, 250, 250));
        txtPicture.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPicture.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        txtMessage.setBackground(new java.awt.Color(250, 250, 250));
        txtMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMessage.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(90, 148, 210));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Choose background color");

        txtBgColor.setBackground(new java.awt.Color(250, 250, 250));
        txtBgColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBgColor.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        txtFontColor.setBackground(new java.awt.Color(250, 250, 250));
        txtFontColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFontColor.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(90, 148, 210));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Choose font color");

        btnCancel.setBackground(new java.awt.Color(90, 148, 210));
        btnCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtInformation.setColumns(20);
        txtInformation.setRows(5);
        txtInformation.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(12, 91, 160)));
        jScrollPane2.setViewportView(txtInformation);

        btnSave.setBackground(new java.awt.Color(90, 148, 210));
        btnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtFontColor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFontColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        rootPanel.add(inputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 360, 470, 660));

        jLabel2.setBackground(new java.awt.Color(245, 245, 245));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\bg_blue.png")); // NOI18N
        rootPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 250, 1536, 830));

        jPanel3.setBackground(new java.awt.Color(110, 89, 222));
        jPanel3.setPreferredSize(new Dimension(screenSize.width / 5 * 4, 150 ));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("List Billboards");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Display all your billboards ");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addContainerGap(1098, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        rootPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 90, 1610, 160));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("We ♥ BBCreator");
        rootPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        rootPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel1btn_homeMouseEntered

    private void jLabel1btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel1btn_homeMouseExited

    private void lb_homebtn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_homebtn_homeMouseEntered

    private void lb_homebtn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_homebtn_homeMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_homeMouseExited

    private void jLabel12lb_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12lb_list_billboardsMouseEntered
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel12lb_list_billboardsMouseEntered

    private void jLabel12lb_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12lb_list_billboardsMouseExited
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel12lb_list_billboardsMouseExited

    private void lb_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_list_billboardsMouseEntered
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_list_billboardsMouseEntered

    private void lb_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_list_billboardsMouseExited
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_list_billboardsMouseExited

    private void jLabel14lb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14lb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel14lb_schedule_billboardsMouseEntered

    private void jLabel14lb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14lb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel14lb_schedule_billboardsMouseExited

    private void lb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_schedule_billboardsMouseEntered

    private void lb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_schedule_billboardsMouseExited

    private void btn_schedule_billboardslb_schedule_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_schedule_billboardslb_schedule_billboardsMouseEntered
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_schedule_billboardslb_schedule_billboardsMouseEntered

    private void btn_schedule_billboardslb_schedule_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_schedule_billboardslb_schedule_billboardsMouseExited
        // TODO add your handling code here:
        btn_schedule_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_schedule_billboardslb_schedule_billboardsMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel16MouseExited

    private void lb_edit_usersjLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_edit_usersjLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_edit_usersjLabel16MouseEntered

    private void lb_edit_usersjLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_edit_usersjLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_edit_usersjLabel16MouseExited

    private void btn_edit_usersjLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_usersjLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_edit_usersjLabel16MouseEntered

    private void btn_edit_usersjLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_usersjLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_edit_usersjLabel16MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTableActionPerformed
        int removeIndex = billboardTable.getSelectedRow();
        if (removeIndex < 0) {
            JOptionPane.showMessageDialog(rootPanel, "Choose a billboard to delete");
        } else if (listBillboard.size() == 0) {
            JOptionPane.showMessageDialog(rootPanel, "No billboards to delete");
        } else {
            listBillboard.remove(removeIndex);
            showTable();
        }
    }//GEN-LAST:event_btnDeleteTableActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void btnEditTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTableActionPerformed
        selectedIndex = billboardTable.getSelectedRow();
        if (listBillboard.size() == 0){
            JOptionPane.showMessageDialog(rootPanel, "Add more billboards to edit");
        }else if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(rootPanel, "Choose a billboard to start editting");
        }else {
            setEditData(listBillboard.get(selectedIndex));
            inputPanel.setVisible(true);
        }
    }//GEN-LAST:event_btnEditTableActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message, information, backgroundColor, fontColor, picture;        
        boolean isOk = true;
        int id = 0;
        
        message = txtMessage.getText();
        information = txtInformation.getText();
        backgroundColor = txtBgColor.getText();
        fontColor = txtFontColor.getText();
        picture = txtPicture.getText();
        
        if(isOk) {
            id = id + 1;
            Date date = new Date();
            Billboard billboard = new Billboard( message, information, backgroundColor, fontColor, id, id, date, date, picture);
            addBillboard(billboard);
            JOptionPane.showMessageDialog(rootPanel, "Add successfully");
            
            txtMessage.setText("");
            txtInformation.setText("");
            txtBgColor.setText("");
            txtFontColor.setText("");
            txtPicture.setText("");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        inputPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String message, information, backgroundColor, fontColor, picture;        
        boolean isOk = true;
        int id = 0;
        
        message = txtMessage.getText();
        information = txtInformation.getText();
        backgroundColor = txtBgColor.getText();
        fontColor = txtFontColor.getText();
        picture = txtPicture.getText();
        
        if(isOk) {
            id = id + 1;
            Date date = new Date();
            Billboard billboard = new Billboard( message, information, backgroundColor, fontColor, id, id, date, date, picture);
            updateBillboard(billboard);
            JOptionPane.showMessageDialog(rootPanel, "Edit successfully");
            
            inputPanel.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    private void btn_list_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardsMousePressed
       
    }//GEN-LAST:event_btn_list_billboardsMousePressed

    private void btn_create_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_create_billboardsMouseEntered
        btn_create_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_create_billboardsMouseEntered

    private void btn_create_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_create_billboardsMouseExited
        // TODO add your handling code here:
        btn_create_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_create_billboardsMouseExited

    private void btn_create_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_create_billboardsMousePressed
        new CreateBillboardsPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_create_billboardsMousePressed

    private void btn_edit_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_usersMousePressed
        new EditUserPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_edit_usersMousePressed

    private void lb_schedule_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_schedule_billboardsMousePressed
        new ScheduleBillboardsPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_schedule_billboardsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListBillboardsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billboardTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteTable;
    private javax.swing.JButton btnEditTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel btn_create_billboards;
    private javax.swing.JPanel btn_edit_users;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_list_billboards;
    private javax.swing.JPanel btn_schedule_billboards;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lb_edit_users;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_list_billboards;
    private javax.swing.JLabel lb_schedule_billboards;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField txtBgColor;
    private javax.swing.JTextField txtFontColor;
    private javax.swing.JTextArea txtInformation;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPicture;
    // End of variables declaration//GEN-END:variables

    public void setEditData(Billboard b) {
        txtMessage.setText(b.getMessage());
        txtInformation.setText(b.getInformation());
        txtBgColor.setText(b.getBackgroundColor());
        txtFontColor.setText(b.getFontColor());
        txtPicture.setText(b.getPicture());
    }

    public void updateBillboard(Billboard b) {
        listBillboard.remove(selectedIndex);
        this.addBillboard(b);
    }

    
}
