/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import model.Billboard;
import model.Schedule;
import model.SortedListModel;

/**
 *
 * @author Asus
 */
public class ScheduleBillboardsPage extends javax.swing.JFrame {

    /**
     * Creates new form ScheduleBillboardsPage
     */
    
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    
    private ArrayList<Schedule> listSchedule;
    private long diffDay = 24 * 60 * 60 * 1000;
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    DateFormat hourFormat = new SimpleDateFormat("HH:mm");
    DateFormat hourDateFormat = new SimpleDateFormat("HH:mm dd-MM-yyyy");
    Date currentDate = new Date();
    
    public ScheduleBillboardsPage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        lbDay1.setText(dateFormat.format(currentDate));
        lbDay2.setText(dateFormat.format(new Date(currentDate.getTime() + diffDay)));
        lbDay3.setText(dateFormat.format(new Date(currentDate.getTime() + 2*diffDay)));
        lbDay4.setText(dateFormat.format(new Date(currentDate.getTime() + 3*diffDay)));
        lbDay5.setText(dateFormat.format(new Date(currentDate.getTime() + 4*diffDay)));
        lbDay6.setText(dateFormat.format(new Date(currentDate.getTime() + 5*diffDay)));
        lbDay7.setText(dateFormat.format(new Date(currentDate.getTime() + 6*diffDay)));
        
        listSchedule = new DAO().getListSchedule();        
        showSchedule();      
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        btn_create_billboards = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_list_billboards = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lb_list_billboards = new javax.swing.JLabel();
        btn_schedule_billboards = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lb_schedule_billboards = new javax.swing.JLabel();
        btn_edit_users = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lb_edit_users = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDay1 = new javax.swing.JList<>();
        lbDay1 = new javax.swing.JLabel();
        lbDay2 = new javax.swing.JLabel();
        lbDay3 = new javax.swing.JLabel();
        lbDay4 = new javax.swing.JLabel();
        lbDay5 = new javax.swing.JLabel();
        lbDay6 = new javax.swing.JLabel();
        lbDay7 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listDay2 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        listDay3 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        listDay4 = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        listDay5 = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        listDay6 = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        listDay7 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JTextField();
        txtScheduleId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTimeLimit = new javax.swing.JTextField();
        txtNextRun = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtBillboardId = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rootPanel.setBackground(new java.awt.Color(255, 255, 255));
        rootPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));
        rootPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setPreferredSize(new Dimension(screenSize.width / 5, screenSize.height));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("BBCreator");
        sidepanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btn_home.setBackground(new java.awt.Color(64, 43, 100));
        btn_home.setPreferredSize(new Dimension(screenSize.width / 5, 50) );
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_homeMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_home_15px_1.png")); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1btn_homeMousePressed(evt);
            }
        });

        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_home.setForeground(new java.awt.Color(204, 204, 204));
        lb_home.setText("Home");
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_homebtn_homeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_home)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_home)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 384, 50));

        btn_create_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_create_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_create_15px.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Create Billboards");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout btn_create_billboardsLayout = new javax.swing.GroupLayout(btn_create_billboards);
        btn_create_billboards.setLayout(btn_create_billboardsLayout);
        btn_create_billboardsLayout.setHorizontalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_create_billboardsLayout.setVerticalGroup(
            btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_create_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_create_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        sidepanel.add(btn_create_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 384, 50));

        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
        btn_list_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_list_billboardslb_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_list_billboardslb_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_list_billboardslb_list_billboardsMousePressed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_list_15px.png")); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12lb_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12lb_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12lb_list_billboardsMousePressed(evt);
            }
        });

        lb_list_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_list_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_list_billboards.setText("List Billboards");
        lb_list_billboards.setToolTipText("");
        lb_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_list_billboardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_list_billboardsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_list_billboardsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_list_billboardsLayout = new javax.swing.GroupLayout(btn_list_billboards);
        btn_list_billboards.setLayout(btn_list_billboardsLayout);
        btn_list_billboardsLayout.setHorizontalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_list_billboards)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btn_list_billboardsLayout.setVerticalGroup(
            btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_list_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_list_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_list_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btn_list_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 384, 50));

        btn_schedule_billboards.setBackground(new java.awt.Color(85, 65, 118));
        btn_schedule_billboards.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_schedule_15px_1.png")); // NOI18N

        lb_schedule_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_schedule_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_schedule_billboards.setText("Schedule Billboards");
        lb_schedule_billboards.setToolTipText("");

        javax.swing.GroupLayout btn_schedule_billboardsLayout = new javax.swing.GroupLayout(btn_schedule_billboards);
        btn_schedule_billboards.setLayout(btn_schedule_billboardsLayout);
        btn_schedule_billboardsLayout.setHorizontalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_schedule_billboards)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        btn_schedule_billboardsLayout.setVerticalGroup(
            btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_schedule_billboardsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_schedule_billboardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_schedule_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btn_schedule_billboards, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 384, 50));

        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
        btn_edit_users.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btn_edit_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_usersjLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_usersjLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_edit_usersMousePressed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\BillboardPanel\\src\\main\\java\\images\\icons8_edit_profile_15px_1.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_edit_usersMousePressed(evt);
            }
        });

        lb_edit_users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_edit_users.setForeground(new java.awt.Color(204, 204, 204));
        lb_edit_users.setText("Edit Users");
        lb_edit_users.setToolTipText("");
        lb_edit_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_edit_usersjLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_edit_usersjLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_edit_usersMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_edit_usersLayout = new javax.swing.GroupLayout(btn_edit_users);
        btn_edit_users.setLayout(btn_edit_usersLayout);
        btn_edit_usersLayout.setHorizontalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_edit_users)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        btn_edit_usersLayout.setVerticalGroup(
            btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_edit_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_edit_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(lb_edit_users, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(btn_edit_usersLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        sidepanel.add(btn_edit_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 384, 50));

        rootPanel.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 384, 1080));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listDay1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(listDay1);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 220));

        lbDay1.setBackground(new java.awt.Color(255, 255, 255));
        lbDay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay1.setText("jLabel7");
        lbDay1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay1.setOpaque(true);
        jPanel2.add(lbDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 70));

        lbDay2.setBackground(new java.awt.Color(255, 255, 255));
        lbDay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay2.setText("jLabel7");
        lbDay2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay2.setOpaque(true);
        jPanel2.add(lbDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 200, 70));

        lbDay3.setBackground(new java.awt.Color(255, 255, 255));
        lbDay3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay3.setText("jLabel7");
        lbDay3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay3.setOpaque(true);
        jPanel2.add(lbDay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, 70));

        lbDay4.setBackground(new java.awt.Color(255, 255, 255));
        lbDay4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay4.setText("jLabel7");
        lbDay4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay4.setOpaque(true);
        jPanel2.add(lbDay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 200, 70));

        lbDay5.setBackground(new java.awt.Color(255, 255, 255));
        lbDay5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay5.setText("jLabel7");
        lbDay5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay5.setOpaque(true);
        jPanel2.add(lbDay5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 200, 70));

        lbDay6.setBackground(new java.awt.Color(255, 255, 255));
        lbDay6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay6.setText("jLabel7");
        lbDay6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(51, 51, 51)));
        lbDay6.setOpaque(true);
        jPanel2.add(lbDay6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, 200, 70));

        lbDay7.setBackground(new java.awt.Color(255, 255, 255));
        lbDay7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDay7.setText("jLabel7");
        lbDay7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        lbDay7.setOpaque(true);
        jPanel2.add(lbDay7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 60, 200, 70));

        listDay2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay2MousePressed(evt);
            }
        });
        jScrollPane9.setViewportView(listDay2);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 220));

        listDay3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay3MousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(listDay3);

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 200, 220));

        listDay4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay4MousePressed(evt);
            }
        });
        jScrollPane11.setViewportView(listDay4);

        jPanel2.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 200, 220));

        listDay5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay5MousePressed(evt);
            }
        });
        jScrollPane12.setViewportView(listDay5);

        jPanel2.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 200, 220));

        listDay6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay6MousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(listDay6);

        jPanel2.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 200, 220));

        listDay7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listDay7.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDay7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listDay7MousePressed(evt);
            }
        });
        jScrollPane14.setViewportView(listDay7);

        jPanel2.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 130, 200, 220));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Schedule List");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 200, 50));

        rootPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 1480, 400));

        inputPanel.setBackground(new java.awt.Color(250, 250, 250));
        inputPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(90, 148, 210));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Schedule your billboard");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(90, 148, 210));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Schedule ID");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(90, 148, 210));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Billboard ID");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(90, 148, 210));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Start time");

        txtStartTime.setBackground(new java.awt.Color(250, 250, 250));
        txtStartTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStartTime.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        txtScheduleId.setEditable(false);
        txtScheduleId.setBackground(new java.awt.Color(250, 250, 250));
        txtScheduleId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtScheduleId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(90, 148, 210));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Time limit (minute)");

        txtTimeLimit.setBackground(new java.awt.Color(250, 250, 250));
        txtTimeLimit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimeLimit.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        txtNextRun.setBackground(new java.awt.Color(250, 250, 250));
        txtNextRun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNextRun.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(90, 148, 210));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Next run (minute)");

        btnCancel.setBackground(new java.awt.Color(90, 148, 210));
        btnCancel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(90, 148, 210));
        btnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtBillboardId.setEditable(false);
        txtBillboardId.setBackground(new java.awt.Color(250, 250, 250));
        txtBillboardId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBillboardId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(90, 148, 210));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Billboard message");

        txtMessage.setEditable(false);
        txtMessage.setBackground(new java.awt.Color(250, 250, 250));
        txtMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMessage.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(12, 91, 160)));

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillboardId, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNextRun, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBillboardId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNextRun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        rootPanel.add(inputPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 700, 940, 350));

        jLabel2.setBackground(new java.awt.Color(245, 245, 245));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\bg_blue.png")); // NOI18N
        rootPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 1536, 830));

        jPanel3.setBackground(new java.awt.Color(110, 89, 222));
        jPanel3.setPreferredSize(new Dimension(screenSize.width / 5 * 4, 150 ));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Edit Schedule");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Schedule billboards to be displayed on the Viewers");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addContainerGap(707, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        rootPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 90, 1610, 160));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("We ♥ BBCreator");
        rootPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        rootPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel1btn_homeMouseEntered

    private void jLabel1btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel1btn_homeMouseExited

    private void jLabel1btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1btn_homeMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabel1btn_homeMousePressed

    private void lb_homebtn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_homebtn_homeMouseEntered

    private void lb_homebtn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_homebtn_homeMouseExited

    private void lb_homebtn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homebtn_homeMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_lb_homebtn_homeMousePressed

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        btn_home.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btn_homeMousePressed

    private void jLabel12lb_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12lb_list_billboardsMouseEntered
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel12lb_list_billboardsMouseEntered

    private void jLabel12lb_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12lb_list_billboardsMouseExited
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel12lb_list_billboardsMouseExited

    private void jLabel12lb_list_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12lb_list_billboardsMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new ListBillboardsPage().setVisible(true);
    }//GEN-LAST:event_jLabel12lb_list_billboardsMousePressed

    private void lb_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_list_billboardsMouseEntered
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_list_billboardsMouseEntered

    private void lb_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_list_billboardsMouseExited
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_list_billboardsMouseExited

    private void lb_list_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_list_billboardsMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new ListBillboardsPage().setVisible(true);
    }//GEN-LAST:event_lb_list_billboardsMousePressed

    private void btn_list_billboardslb_list_billboardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardslb_list_billboardsMouseEntered
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_list_billboardslb_list_billboardsMouseEntered

    private void btn_list_billboardslb_list_billboardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardslb_list_billboardsMouseExited
        // TODO add your handling code here:
        btn_list_billboards.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_list_billboardslb_list_billboardsMouseExited

    private void btn_list_billboardslb_list_billboardsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_billboardslb_list_billboardsMousePressed
        // TODO add your handling code here:
        setVisible(false);
        new ListBillboardsPage().setVisible(true);
    }//GEN-LAST:event_btn_list_billboardslb_list_billboardsMousePressed

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_jLabel16MouseExited

    private void lb_edit_usersjLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_edit_usersjLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lb_edit_usersjLabel16MouseEntered

    private void lb_edit_usersjLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_edit_usersjLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lb_edit_usersjLabel16MouseExited

    private void btn_edit_usersjLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_usersjLabel16MouseEntered
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_btn_edit_usersjLabel16MouseEntered

    private void btn_edit_usersjLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_usersjLabel16MouseExited
        // TODO add your handling code here:
        btn_edit_users.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_btn_edit_usersjLabel16MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void listDay7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay7MousePressed
        listDay1.clearSelection();
        listDay2.clearSelection();
        listDay3.clearSelection();
        listDay4.clearSelection();
        listDay5.clearSelection();
        listDay6.clearSelection();
        
        getSelectedValue(listDay7);
        
        
        
    }//GEN-LAST:event_listDay7MousePressed

    private void listDay6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay6MousePressed
        listDay1.clearSelection();
        listDay2.clearSelection();
        listDay3.clearSelection();
        listDay4.clearSelection();
        listDay5.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay6);
    }//GEN-LAST:event_listDay6MousePressed

    private void listDay5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay5MousePressed
        listDay1.clearSelection();
        listDay2.clearSelection();
        listDay3.clearSelection();
        listDay4.clearSelection();
        listDay6.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay5);
    }//GEN-LAST:event_listDay5MousePressed

    private void listDay4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay4MousePressed
        listDay1.clearSelection();
        listDay2.clearSelection();
        listDay3.clearSelection();
        listDay6.clearSelection();
        listDay5.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay4);
    }//GEN-LAST:event_listDay4MousePressed

    private void listDay3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay3MousePressed
        listDay1.clearSelection();
        listDay2.clearSelection();
        listDay6.clearSelection();
        listDay4.clearSelection();
        listDay5.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay3);
    }//GEN-LAST:event_listDay3MousePressed

    private void listDay2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay2MousePressed
        listDay1.clearSelection();
        listDay6.clearSelection();
        listDay3.clearSelection();
        listDay4.clearSelection();
        listDay5.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay2);
    }//GEN-LAST:event_listDay2MousePressed

    private void listDay1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDay1MousePressed
        listDay2.clearSelection();
        listDay6.clearSelection();
        listDay3.clearSelection();
        listDay4.clearSelection();
        listDay5.clearSelection();
        listDay7.clearSelection();
        
        getSelectedValue(listDay1);
    }//GEN-LAST:event_listDay1MousePressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
        inputPanel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int scheduleId , timeLimit, nextRun ; 
        String startTime;
        boolean isOk = true;
       
        scheduleId = Integer.parseInt(txtScheduleId.getText());
        timeLimit = Integer.parseInt(txtTimeLimit.getText());
        nextRun = Integer.parseInt(txtNextRun.getText());        
        startTime = txtStartTime.getText();
       
              
        if (txtScheduleId.getText().equals("")){
            isOk = false;
        }

        if(isOk) {            
            Date updateAt = new Date();
            for (Schedule s : listSchedule){
                if (s.getScheduleId() == scheduleId){
                    System.out.println(""+ scheduleId);
                    s.setUpdateAt(updateAt);
                    s.setTimeLimit(timeLimit);
                    s.setNextRun(nextRun);
                    s.setStartTime(startTime);
                }
            }
            
            JOptionPane.showMessageDialog(rootPanel, "Edit successfully");
            showSchedule();
            inputPanel.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPanel, "Choose schedule to edit");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void lb_edit_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_edit_usersMousePressed
        new EditUserPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_edit_usersMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleBillboardsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleBillboardsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel btn_create_billboards;
    private javax.swing.JPanel btn_edit_users;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_list_billboards;
    private javax.swing.JPanel btn_schedule_billboards;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDay1;
    private javax.swing.JLabel lbDay2;
    private javax.swing.JLabel lbDay3;
    private javax.swing.JLabel lbDay4;
    private javax.swing.JLabel lbDay5;
    private javax.swing.JLabel lbDay6;
    private javax.swing.JLabel lbDay7;
    private javax.swing.JLabel lb_edit_users;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_list_billboards;
    private javax.swing.JLabel lb_schedule_billboards;
    private javax.swing.JList<String> listDay1;
    private javax.swing.JList<String> listDay2;
    private javax.swing.JList<String> listDay3;
    private javax.swing.JList<String> listDay4;
    private javax.swing.JList<String> listDay5;
    private javax.swing.JList<String> listDay6;
    private javax.swing.JList<String> listDay7;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTextField txtBillboardId;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtNextRun;
    private javax.swing.JTextField txtScheduleId;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JTextField txtTimeLimit;
    // End of variables declaration//GEN-END:variables
    
    
    public void getSelectedValue(JList list) {
        int index = list.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        String str = (String) list.getSelectedValue();
        System.out.println("Value Selected: " + str);
        
        String[] elements = str.split("   ");
        String scheduleId = elements[2];
        
        for (Schedule s : listSchedule) {
            if (scheduleId.equals(Integer.toString(s.getScheduleId()))){
                txtScheduleId.setText(scheduleId);
                txtNextRun.setText(Integer.toString(s.getNextRun()));
                txtTimeLimit.setText(Integer.toString(s.getTimeLimit()));
                txtStartTime.setText(hourDateFormat.format(s.getStartTime()));
            }
        }
        
        inputPanel.setVisible(true);
        
        
    }
    
//    public void updateSchedule(Schedule s){
//        listSchedule.remove(selectedIndex);
//        this.addBillboard(b);
//    }
    public void showSchedule(){
        listSchedule = new DAO().processListSchedule(listSchedule);
        
        final SortedListModel scheduleModel1 = new SortedListModel();
        final SortedListModel scheduleModel2 = new SortedListModel();
        final SortedListModel scheduleModel3 = new SortedListModel();
        final SortedListModel scheduleModel4 = new SortedListModel();
        final SortedListModel scheduleModel5 = new SortedListModel();
        final SortedListModel scheduleModel6 = new SortedListModel();
        final SortedListModel scheduleModel7 = new SortedListModel();
        for (Schedule s : listSchedule) {
//            model.addRow(new Object[]{
//                b.getBillboardId(), b.getUserId(), b.getMessage(), b.getInformation(), b.getBackgroundColor(), b.getFontColor(), b.getCreatedAt(), b.getUpdateAt(), b.getPicture()
//            });
//            
//            ArrayList<Date> runTime = s.getRunTime();
            ArrayList<Date> startRun = new ArrayList<Date>();                    
            startRun.addAll(s.getStartRun());
            ArrayList<Date> endRun = new ArrayList<Date>(); 
            endRun.addAll(s.getEndRun());
            
            
            
 //           for(Date r :runTime){
            for(int i = 0; i < startRun.size(); i++){
                if (dateFormat.format(startRun.get(i)).equals(lbDay1.getText())){                    
                    scheduleModel1.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());                    
                }
                    
                else if (dateFormat.format(startRun.get(i)).equals(lbDay2.getText())){                    
                    scheduleModel2.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }else if (dateFormat.format(startRun.get(i)).equals(lbDay3.getText())){                    
                    scheduleModel3.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }else if (dateFormat.format(startRun.get(i)).equals(lbDay4.getText())){                    
                    scheduleModel4.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }else if (dateFormat.format(startRun.get(i)).equals(lbDay5.getText())){                    
                    scheduleModel5.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }else if (dateFormat.format(startRun.get(i)).equals(lbDay6.getText())){                    
                    scheduleModel6.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }else if (dateFormat.format(startRun.get(i)).equals(lbDay7.getText())){                    
                    scheduleModel7.addElement(hourFormat.format(startRun.get(i)) + "-"+ hourFormat.format(endRun.get(i))+ "   |   " + s.getScheduleId());
                    
                    
                }
            }
            
            
        }
        listDay1.setModel(scheduleModel1);
        listDay2.setModel(scheduleModel2);
        listDay3.setModel(scheduleModel3);
        listDay4.setModel(scheduleModel4);
        listDay5.setModel(scheduleModel5);
        listDay6.setModel(scheduleModel6);
        listDay7.setModel(scheduleModel7);
    }

}
